#!/usr/bin/env python3
"""
Script to add Profile & Account test cases to TestRail for Minebit project.
All test cases are written in upper-intermediate English.
"""

import json
import subprocess

# TestRail API configuration
TESTRAIL_URL = "https://nexttcode.testrail.io"
EMAIL = "ihor.so@nextcode.tech"
API_KEY = "WI8RMbuUOuOgsqFwVx2C-7y4HBmZrSolpj1SK9TbT"

# Section ID for "Profile & Account"
SECTION_ID = 6840

def add_test_case(case_data):
    """Add a test case to TestRail"""
    cmd = [
        'curl', '-s', '-u', f"{EMAIL}:{API_KEY}",
        '-H', 'Content-Type: application/json',
        '-X', 'POST',
        '-d', json.dumps(case_data),
        f"{TESTRAIL_URL}/index.php?/api/v2/add_case/{SECTION_ID}"
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"error": f"Failed to parse response: {result.stdout[:200]}"}

# Test cases for Profile & Account section
# 6 test cases as specified by the user
test_cases = [
    {
        "title": "Change password with valid current password",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Authorized player logged in</p><p>Player knows current password</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Profile → Security Settings</p>",
                "expected": "<p>Security settings page loads</p>"
            },
            {
                "content": "<p>Enter current password correctly in 'Current Password' field</p>",
                "expected": "<p>Current password accepted</p>"
            },
            {
                "content": "<p>Enter new password meeting complexity requirements</p>",
                "expected": "<p>New password meets requirements</p>"
            },
            {
                "content": "<p>Confirm new password in confirmation field</p>",
                "expected": "<p>Passwords match</p>"
            },
            {
                "content": "<p>Click 'Save Changes' or equivalent button</p>",
                "expected": "<p>Password change successful</p>"
            },
            {
                "content": "<p>Attempt to login with new password</p>",
                "expected": "<p>Login successful with new password</p>"
            }
        ]
    },
    {
        "title": "Change password - invalid current password rejection",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Authorized player logged in</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Profile → Security Settings</p>",
                "expected": "<p>Security settings page loads</p>"
            },
            {
                "content": "<p>Enter incorrect current password in 'Current Password' field</p>",
                "expected": "<p>Invalid password entered</p>"
            },
            {
                "content": "<p>Enter new password in 'New Password' field</p>",
                "expected": "<p>New password entered</p>"
            },
            {
                "content": "<p>Confirm new password</p>",
                "expected": "<p>Confirmation entered</p>"
            },
            {
                "content": "<p>Click 'Save Changes' or equivalent button</p>",
                "expected": "<p>Error message 'Current password is incorrect' displayed</p>"
            },
            {
                "content": "<p>Verify password remains unchanged</p>",
                "expected": "<p>Password not changed, can still login with original password</p>"
            }
        ]
    },
    {
        "title": "Two-Factor Authentication (2FA) enable/disable flow",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Authorized player logged in</p><p>2FA feature is available and enabled for the platform</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Security Settings → Two-Factor Authentication (2FA)</p>",
                "expected": "<p>2FA settings page loads</p>"
            },
            {
                "content": "<p>Click 'Enable 2FA' button</p>",
                "expected": "<p>QR code and setup instructions displayed</p>"
            },
            {
                "content": "<p>Scan QR code with authenticator app (Google Authenticator, Authy, etc.)</p>",
                "expected": "<p>Account added to authenticator app</p>"
            },
            {
                "content": "<p>Enter 6-digit code generated by authenticator app</p>",
                "expected": "<p>Code verification successful</p>"
            },
            {
                "content": "<p>Verify 2FA status changes to 'Enabled'</p>",
                "expected": "<p>2FA successfully enabled</p>"
            },
            {
                "content": "<p>Logout and attempt to login</p>",
                "expected": "<p>Login requires 2FA code after entering credentials</p>"
            },
            {
                "content": "<p>Navigate back to 2FA settings and click 'Disable 2FA'</p>",
                "expected": "<p>2FA disabled successfully</p>"
            },
            {
                "content": "<p>Logout and login again</p>",
                "expected": "<p>Login no longer requires 2FA code</p>"
            }
        ]
    },
    {
        "title": "Email address verification process",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Player with unverified email address</p><p>Access to email inbox</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Profile → Personal Information</p>",
                "expected": "<p>Personal information page loads, email shows 'Unverified' status</p>"
            },
            {
                "content": "<p>Click 'Verify Email' button/link</p>",
                "expected": "<p>Confirmation message 'Verification email sent' displayed</p>"
            },
            {
                "content": "<p>Check email inbox for verification message</p>",
                "expected": "<p>Email received with verification link</p>"
            },
            {
                "content": "<p>Click verification link in email</p>",
                "expected": "<p>Browser redirects to verification confirmation page</p>"
            },
            {
                "content": "<p>Return to Profile → Personal Information page</p>",
                "expected": "<p>Email status now shows 'Verified'</p>"
            },
            {
                "content": "<p>Refresh page to confirm persistent status</p>",
                "expected": "<p>Email remains 'Verified' after refresh</p>"
            }
        ]
    },
    {
        "title": "Phone number update and verification",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Authorized player logged in</p><p>Access to mobile device for SMS reception</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Profile → Contact Information</p>",
                "expected": "<p>Contact information page loads</p>"
            },
            {
                "content": "<p>Add or update phone number in phone field</p>",
                "expected": "<p>Phone number entered</p>"
            },
            {
                "content": "<p>Click 'Request Verification Code' or similar button</p>",
                "expected": "<p>SMS sent to provided phone number</p>"
            },
            {
                "content": "<p>Enter 4-6 digit verification code received via SMS</p>",
                "expected": "<p>Code accepted</p>"
            },
            {
                "content": "<p>Click 'Save Changes' or 'Verify' button</p>",
                "expected": "<p>Phone number verified and saved</p>"
            },
            {
                "content": "<p>Verify phone status shows 'Verified'</p>",
                "expected": "<p>Phone number marked as verified in profile</p>"
            }
        ]
    },
    {
        "title": "Date of birth validation (once set, cannot be changed)",
        "priority_id": 3,  # High
        "type_id": 11,  # Acceptance
        "custom_preconds": "<p>Player with date of birth already set during registration</p>",
        "custom_steps_separated": [
            {
                "content": "<p>Navigate to Profile → Personal Information</p>",
                "expected": "<p>Personal information page loads</p>"
            },
            {
                "content": "<p>Locate Date of Birth field</p>",
                "expected": "<p>Date of Birth field visible with pre-filled value</p>"
            },
            {
                "content": "<p>Attempt to click or focus on Date of Birth field</p>",
                "expected": "<p>Field is read-only or disabled (cannot be edited)</p>"
            },
            {
                "content": "<p>Check for tooltip or informational message</p>",
                "expected": "<p>Tooltip or message explains 'Date of birth cannot be changed after registration'</p>"
            },
            {
                "content": "<p>Attempt alternative editing methods (right-click, keyboard shortcuts)</p>",
                "expected": "<p>Date of birth remains uneditable</p>"
            }
        ]
    }
]

# Add test cases
print(f"Adding {len(test_cases)} test cases to TestRail (Profile & Account section)...\n")

for i, case in enumerate(test_cases, 1):
    print(f"[{i}/{len(test_cases)}] Adding: {case['title']}")
    result = add_test_case(case)
    
    if 'error' in result:
        print(f"  ❌ Error: {result['error']}")
    else:
        print(f"  ✅ Success! Case ID: {result.get('id', 'Unknown')}")
    
print("\nDone!")